### ISSUE TITLE
Should this working group be responsible for Debugging or should it have it's own WG

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/tracing-wg#51]
From https://github.com/nodejs/node/issues/7072

> Current status: v8_inspector support has been merged in to master @ #6792, as yet it's not in v6.x but I'm anticipating that it soon will be. 
> @rvagg 

There are a bunch of hanging questions regarding the debugger and it would prove helpful to a working group to focus on it. It is likely that there is an overlap in interest between tracing + debugging... but enough of a difference that it might make sense to spin up a new WG.

Would be very interested to hear the thoughts of @nodejs/tracing

**Comment by AndreasMadsen** [comment]
The Tracing WG already deals with some debugging initiatives, such as AsyncWrap which can be used for both debugging and profiling. Having the "Chrome" Debugger in this working group would be logical, however it also has a lot of public interrest which may diverge our resources.

I think if a debugging working group is created, it has to be very specific for example "standardizing the debugging protocol". Otherwise it will unclear which working group is responsible for what. There is already confusion about what the post-mortem WG is responsible for and the Tracing WG is about.

**Comment by pmuellr** [comment]
This topic is on the agenda for [this week's call](https://github.com/nodejs/tracing-wg/issues/49) - "Expanding scope to Diagnostics WG"

**Comment by joshgav** [comment]
See also #46 and #47 where I've started implementing what a Diagnostics WG might focus on and look like.

I think a single Diagnostics WG with teams focused on different domains (e.g. tracing, post-mortem, protocol/API, step debugging) will lead to good results and experience for Node, for contributors, and for users; help us share and collaborate better; and avoid redundancy and overlap.

**Comment by eljefedelrodeodeljefe** [comment]
In any case, I'd like to help.

**Comment by TheAlphaNerd** [comment]
Closing. Discussion to continue in https://github.com/nodejs/tracing-wg/issues/46
